update actions for push helm package to ECR

diff --git a/.github/workflows/02-eks-aws-deploy.yml b/.github/workflows/02-eks-aws-deploy.yml
--- a/.github/workflows/02-eks-aws-deploy.yml
+++ b/.github/workflows/02-eks-aws-deploy.yml
@@ -1,15 +1,17 @@
 
-name: 2) EKS AWS   Deploy to EKS Cluster
+name: 2) EKS AWS Deploy to EKS Cluster
 description: Deploy the application to the EKS cluster from image ECR, using the helm deployment (in .helm folder)
 
 on:
   workflow_dispatch:
+    inputs:
+      version_tag:
+        description: 'Image tag to deploy (from ECR). If not provided, "latest" will be used'
+        required: false
+        type: string
 
 env:
-  #DEPLOY_NAME: ${{ github.ref_name }}
-  # TODO: change to main or develop, or add other branches
-  DEPLOY_NAME: "${{ github.ref_name == 'main' && 'main' || github.ref_name == 'develop' && 'develop' || 'develop'  }}"
-  IMAGE_TAG: latest
+  IMAGE_TAG: "${{ github.event.inputs.version_tag || 'latest' }}"
 
 permissions:
   contents: read
@@ -117,7 +119,7 @@ jobs:
 
     - name: Deploy to EKS
       env:
-        ECR_REPOSITORY: ${{ vars.APP_NAME }}/${{ env.DEPLOY_NAME }}
+        ECR_REPOSITORY: ${{ vars.APP_NAME }}
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         IMAGE_TAG: ${{ env.IMAGE_TAG }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -140,13 +142,20 @@ jobs:
       run: |
         echo "🏗️ Environment: ${{ vars.ENVIRONMENT }}"
         echo "🚀 Desplegando desde rama: ${{ github.ref_name }}"
-        echo "📦 App name / deployment: ${{ vars.APP_NAME }} / ${{ env.DEPLOY_NAME }}"
+        echo "📦 App name: ${{ vars.APP_NAME }}"
         echo "🏷️ Image tag: ${{ env.IMAGE_TAG }}"
         echo "🏷️ EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}"
         echo "🏷️ EKS_NAMESPACE: ${{ vars.EKS_NAMESPACE }}"
         echo "🏷️ ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}"
         echo "🏷️ ECR_REGISTRY: ${{ env.ECR_REGISTRY }}"
 
+        echo " > Check existing image in ECR..."
+        if ! aws ecr describe-images --repository-name $ECR_REPOSITORY --image-ids imageTag=$IMAGE_TAG >/dev/null 2>&1; then
+          echo "❌ Image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG does not exist in ECR. Aborting deployment."
+          exit 1
+        fi
+        echo "👉🏻 ✅ Image $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG "
+        
         cd .helm
 
         # Install or Update Helm chart values with the correct image details
@@ -155,17 +164,17 @@ jobs:
         envsubst < values.yaml | helm template . --debug --values - 
 
         echo " > Checking if deployment exists..."
-        if kubectl -n ${{ vars.EKS_NAMESPACE }} get secrets | grep ${{ vars.APP_NAME }}-${{ env.DEPLOY_NAME }}; then
+        if kubectl -n ${{ vars.EKS_NAMESPACE }} get secrets | grep ${{ vars.APP_NAME }}; then
           echo " > Deployment exists."
           echo " > Updating Helm chart values with image details..."
-          envsubst < values.yaml | helm upgrade ${{ vars.APP_NAME }}-${{ env.DEPLOY_NAME }} . --namespace ${{ vars.EKS_NAMESPACE }} --create-namespace --values -
+          envsubst < values.yaml | helm upgrade ${{ vars.APP_NAME }} . --namespace ${{ vars.EKS_NAMESPACE }} --create-namespace --values -
           # Force restart pods to pick up new environment variables from updated secrets/configmaps
           echo " > Restarting pods to pick up new environment variables..."
           kubectl -n ${{ vars.EKS_NAMESPACE }} rollout restart deployment ${{ vars.APP_NAME }}
         else
           echo " > Deployment does not exist."
           echo " > Installing Helm chart with image details..."
-          envsubst < values.yaml | helm install ${{ vars.APP_NAME }}-${{ env.DEPLOY_NAME }} . --debug --namespace ${{ vars.EKS_NAMESPACE }} --create-namespace --values -
+          envsubst < values.yaml | helm install ${{ vars.APP_NAME }} . --debug --namespace ${{ vars.EKS_NAMESPACE }} --create-namespace --values -
         fi
 
         #kubectl -n ${{ vars.EKS_NAMESPACE }} get pods -l app.kubernetes.io/name=${{ vars.APP_NAME }}
