update main (#2)
* add env var EMAIL_HOST_PASSWORD

* add env var EMAIL_HOST_PASSWORD 2

* add env var EMAIL_HOST_PASSWORD 3

* get credentials

* filter Organization Identity

* order by in get credentials

* validado

* revoke credential endpoint

* add new endpoints to ISBE-ART-00103.md

* integrate connector

* add IDENTFY_CONNECTOR_API_KEY

* add IDENTFY_CONNECTOR_API_KEY 2

* add IDENTFY_CONNECTOR_API_KEY 3

* return isbe-representative-vc

* use _isbe_identier_to_vc_type

* look and feel ISBE

* fix: mejora calidad logo y se quitan referencias izertis/identfy

* use ARN_CERT

* CI - insert header

* CI - insert header

* CI - insert header

* CI - insert header

* CI - insert header

* chore: Insert standard header into code files

* CI - insert header

* chore: Insert standard header into code files

* send email reset and welcome

* doc: añadir copyright al fichero de artefacto

* fix: /api/v1/health -> /health

* bug in comment for JS

* update insert-header-in-code-files.py

* add control with powers

* chore: Insert standard header into code files

* rename to identfy-credentials-issuer

* review integrate tmf and connector

* refine issuer credentials

* add settools

* integrate management service

* add env vars

* config EMAIL_USE_TLS and EMAIL_USE_SSL

* use validate token

* add api version in get credential

* add api version in get credential 2

* revoke credential

* redefine checks powers

* delete TODOs

* use name or user in payload token

* fix: add preauth-code to qr

* fix: wrong openapi parameter

---------

Co-authored-by: Alberto Rodríguez Ludeiro <36158606+ludeiro@users.noreply.github.com>
Co-authored-by: Yeray Rodríguez <yerayrodriguez@gmail.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

diff --git a/.github/workflows/02-eks-aws-deploy.yml b/.github/workflows/02-eks-aws-deploy.yml
--- a/.github/workflows/02-eks-aws-deploy.yml
+++ b/.github/workflows/02-eks-aws-deploy.yml
@@ -55,16 +55,16 @@ jobs:
           echo "🛑 HOST_NAME is not set in variables"
           exit 1
         fi
-        if [[ -z "${{ vars.ARN_CERT }}" ]]; then
-          echo "🛑 ARN_CERT is not set in variables"
-          exit 1
-        fi
         if [[ -z "${{ vars.EKS_CLUSTER_NAME }}" ]]; then
           echo "🛑 EKS_CLUSTER_NAME is not set in variables"
           exit 1
         fi
         if [[ -z "${{ vars.EKS_NAMESPACE }}" ]]; then
           echo "🛑 EKS_NAMESPACE is not set in variables"
+          exit 1
+        fi
+        if [[ -z "${{ vars.ARN_CERT }}" ]]; then
+          echo "🛑 ARN_CERT is not set in variables"
           exit 1
         fi
         if [[ -z "${{ vars.ALLOWED_HOSTS }}" ]]; then
@@ -95,6 +95,10 @@ jobs:
           echo "🛑 IDENTFY_CONNECTOR_API_URL is not set in variables"
           exit 1
         fi
+        if [[ -z "${{ secrets.IDENTFY_CONNECTOR_API_KEY }}" ]]; then
+          echo "🛑 IDENTFY_CONNECTOR_API_KEY is not set in variables"
+          exit 1
+        fi
         if [[ -z "${{ vars.TMF_API_URL }}" ]]; then
           echo "🛑 TMF_API_URL is not set in variables"
           exit 1
@@ -103,6 +107,39 @@ jobs:
           echo "🛑 KEYCLOAK_JWKS_URL is not set in variables"
           exit 1
         fi
+        if [[ -z "${{ secrets.EMAIL_HOST_PASSWORD }}" ]]; then
+          echo "🛑 EMAIL_HOST_PASSWORD is not set in secrets"
+          exit 1
+        fi
+        if [[ -z "${{ vars.MANAGEMENT_API_URL }}" ]]; then
+          echo "🛑 MANAGEMENT_API_URL is not set in variables"
+          exit 1
+        fi
+        if [[ -z "${{ vars.EMAIL_HOST }}" ]]; then
+          echo "🛑 EMAIL_HOST is not set in variables"
+          exit 1
+        fi
+        if [[ -z "${{ vars.EMAIL_PORT }}" ]]; then
+          echo "🛑 EMAIL_PORT is not set in variables 
+          exit 1"
+        fi
+        if [[ -z "${{ vars.EMAIL_USE_TLS }}" ]]; then
+          echo "🛑 EMAIL_USE_TLS is not set in variables"
+          exit 1
+        fi
+        if [[ -z "${{ vars.EMAIL_USE_SSL }}" ]]; then
+          echo "🛑 EMAIL_USE_SSL is not set in variables"
+          exit 1
+        fi
+        if [[ -z "${{ vars.EMAIL_HOST_USER }}" ]]; then
+          echo "🛑 EMAIL_HOST_USER is not set in variables"
+          exit 1
+        fi
+        if [[ -z "${{ vars.DEFAULT_FROM_EMAIL }}" ]]; then
+          echo "🛑 DEFAULT_FROM_EMAIL is not set in variables"  
+          exit 1
+        fi
+        echo "✅ All required variables and secrets are set."
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
@@ -133,12 +170,20 @@ jobs:
         BACKEND_DOMAIN: ${{ vars.BACKEND_DOMAIN }}
         CSRF_TRUSTED_ORIGINS: ${{ vars.CSRF_TRUSTED_ORIGINS }}
         CORS_ALLOWED_ORIGINS: ${{ vars.CORS_ALLOWED_ORIGINS }}
-        CONNECTOR_URL: ${{ vars.CONNECTOR_URL }}
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
         DATABASE_URL: ${{ secrets.DATABASE_URL }}
         IDENTFY_CONNECTOR_API_URL: ${{ vars.IDENTFY_CONNECTOR_API_URL }}
+        IDENTFY_CONNECTOR_API_KEY: ${{ secrets.IDENTFY_CONNECTOR_API_KEY }}
         TMF_API_URL: ${{ vars.TMF_API_URL }}
-        KEYCLOAK_JWKS_URL: ${{ vars.KEYCLOAK_JWKS_URL }}   
+        KEYCLOAK_JWKS_URL: ${{ vars.KEYCLOAK_JWKS_URL }}
+        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
+        MANAGEMENT_API_URL: ${{ vars.MANAGEMENT_API_URL }}
+        EMAIL_HOST: ${{ vars.EMAIL_HOST }}
+        EMAIL_PORT: ${{ vars.EMAIL_PORT }}
+        EMAIL_USE_TLS: ${{ vars.EMAIL_USE_TLS }}
+        EMAIL_USE_SSL: ${{ vars.EMAIL_USE_SSL }}
+        EMAIL_HOST_USER: ${{ vars.EMAIL_HOST_USER }}
+        DEFAULT_FROM_EMAIL: ${{ vars.DEFAULT_FROM_EMAIL }}
       run: |
         echo "🏗️ Environment: ${{ vars.ENVIRONMENT }}"
         echo "🚀 Desplegando desde rama: ${{ github.ref_name }}"
